//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pro_motor
    {
        public int id { get; set; }
        public Nullable<int> fk_cat_id { get; set; }
        public string title { get; set; }
        public string company { get; set; }
        public string photo { get; set; }
        public Nullable<int> km { get; set; }
        public Nullable<int> year { get; set; }
        public string body { get; set; }
        public string engine { get; set; }
        public string fuel { get; set; }
        public string hp { get; set; }
        public string phoneno { get; set; }
        public string price { get; set; }
        public string description { get; set; }
        public string location { get; set; }
        public string checkbox { get; set; }
    }
}
