//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets6F1A81ECAEF64BA74CB5F84DCE562A9E4AA5F91D0E489B920C3202ECA3C3E33F))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// The type contains views for EntitySets and AssociationSets that were generated at design time.
    /// </Summary>
    public sealed class ViewsForBaseEntitySets6F1A81ECAEF64BA74CB5F84DCE562A9E4AA5F91D0E489B920C3202ECA3C3E33F : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// The constructor stores the views for the extents and also the hash values generated based on the metadata and mapping closure and views.
        /// </Summary>
        public ViewsForBaseEntitySets6F1A81ECAEF64BA74CB5F84DCE562A9E4AA5F91D0E489B920C3202ECA3C3E33F()
        {
            this.EdmEntityContainerName = "SellNbuyEntities";
            this.StoreEntityContainerName = "SellNbuyModelStoreContainer";
            this.HashOverMappingClosure = "0d445372b5da4f004224e3406a2415ef9b3d8da61bbd9ef276dcf1bd3e27c374";
            this.HashOverAllExtentViews = "e1f5201966564727af0c0a50e19a88261e479e6a3074ff91bb02a315f89453c9";
            this.ViewCount = 10;
        }
        
        /// <Summary>
        /// The method returns the view for the index given.
        /// </Summary>
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                return GetView0();
            }
            if ((index == 1))
            {
                return GetView1();
            }
            if ((index == 2))
            {
                return GetView2();
            }
            if ((index == 3))
            {
                return GetView3();
            }
            if ((index == 4))
            {
                return GetView4();
            }
            if ((index == 5))
            {
                return GetView5();
            }
            if ((index == 6))
            {
                return GetView6();
            }
            if ((index == 7))
            {
                return GetView7();
            }
            if ((index == 8))
            {
                return GetView8();
            }
            if ((index == 9))
            {
                return GetView9();
            }
            throw new System.IndexOutOfRangeException();
        }
        
        /// <Summary>
        /// return view for SellNbuyModelStoreContainer.classifieds
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView0()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("SellNbuyModelStoreContainer.classifieds", @"
    SELECT VALUE -- Constructing classifieds
        [SellNbuyModel.Store.classifieds](T1.classifieds_id, T1.classifieds_cat)
    FROM (
        SELECT 
            T.id AS classifieds_id, 
            T.cat AS classifieds_cat, 
            True AS _from0
        FROM SellNbuyEntities.classifieds AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for SellNbuyEntities.classifieds
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView1()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("SellNbuyEntities.classifieds", @"
    SELECT VALUE -- Constructing classifieds
        [SellNbuyModel.classified](T1.classified_id, T1.classified_cat)
    FROM (
        SELECT 
            T.id AS classified_id, 
            T.cat AS classified_cat, 
            True AS _from0
        FROM SellNbuyModelStoreContainer.classifieds AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for SellNbuyModelStoreContainer.community
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView2()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("SellNbuyModelStoreContainer.community", @"
    SELECT VALUE -- Constructing community
        [SellNbuyModel.Store.community](T1.community_id, T1.community_cat)
    FROM (
        SELECT 
            T.id AS community_id, 
            T.cat AS community_cat, 
            True AS _from0
        FROM SellNbuyEntities.communities AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for SellNbuyEntities.communities
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView3()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("SellNbuyEntities.communities", @"
    SELECT VALUE -- Constructing communities
        [SellNbuyModel.community](T1.community_id, T1.community_cat)
    FROM (
        SELECT 
            T.id AS community_id, 
            T.cat AS community_cat, 
            True AS _from0
        FROM SellNbuyModelStoreContainer.community AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for SellNbuyModelStoreContainer.job
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView4()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("SellNbuyModelStoreContainer.job", @"
    SELECT VALUE -- Constructing job
        [SellNbuyModel.Store.job](T1.job_id, T1.job_cat)
    FROM (
        SELECT 
            T.id AS job_id, 
            T.cat AS job_cat, 
            True AS _from0
        FROM SellNbuyEntities.jobs AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for SellNbuyEntities.jobs
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView5()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("SellNbuyEntities.jobs", @"
    SELECT VALUE -- Constructing jobs
        [SellNbuyModel.job](T1.job_id, T1.job_cat)
    FROM (
        SELECT 
            T.id AS job_id, 
            T.cat AS job_cat, 
            True AS _from0
        FROM SellNbuyModelStoreContainer.job AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for SellNbuyModelStoreContainer.motor
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView6()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("SellNbuyModelStoreContainer.motor", @"
    SELECT VALUE -- Constructing motor
        [SellNbuyModel.Store.motor](T1.motor_id, T1.motor_cat)
    FROM (
        SELECT 
            T.id AS motor_id, 
            T.cat AS motor_cat, 
            True AS _from0
        FROM SellNbuyEntities.motors AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for SellNbuyEntities.motors
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView7()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("SellNbuyEntities.motors", @"
    SELECT VALUE -- Constructing motors
        [SellNbuyModel.motor](T1.motor_id, T1.motor_cat)
    FROM (
        SELECT 
            T.id AS motor_id, 
            T.cat AS motor_cat, 
            True AS _from0
        FROM SellNbuyModelStoreContainer.motor AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for SellNbuyModelStoreContainer.property
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView8()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("SellNbuyModelStoreContainer.property", @"
    SELECT VALUE -- Constructing property
        [SellNbuyModel.Store.property](T1.property_id, T1.property_cat)
    FROM (
        SELECT 
            T.id AS property_id, 
            T.cat AS property_cat, 
            True AS _from0
        FROM SellNbuyEntities.properties AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for SellNbuyEntities.properties
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView9()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("SellNbuyEntities.properties", @"
    SELECT VALUE -- Constructing properties
        [SellNbuyModel.property](T1.property_id, T1.property_cat)
    FROM (
        SELECT 
            T.id AS property_id, 
            T.cat AS property_cat, 
            True AS _from0
        FROM SellNbuyModelStoreContainer.property AS T
    ) AS T1");
        }
    }
}
